services:

  backend:
    image: khoa2k4/project-it3180:backend_resident_fee-service_1.0
    restart: unless-stopped
    networks:
      - test-network
    ports:
      - "8080:8080"

networks:
  test-network:
    driver: bridge
