name: Deploy ProjectIT3180

on:
  push:
    branches: [main]
    paths:
      - "src/backend/**"

  pull_request:
    branches: [main]
    types: [closed]
    paths:
      - "src/backend/**"

jobs:
  deploy:
    if: |
      github.event_name == 'push'
      || (github.event_name == 'pull_request' && github.event.pull_request.merged == true)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build & push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./src/backend/resident_fee-service
          file: ./src/backend/resident_fee-service/Dockerfile
          push: true
          tags: khoa2k4/project-it3180:backend_resident_fee-service_1.0

      - name: Redeploy
        run: |
          curl -X POST https://backboard.railway.app/graphql/v2 \
            -H "Authorization: Bearer ${{ secrets.RAILWAY_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d '{
              "query": "mutation serviceInstanceRedeploy($environmentId: String!, $serviceId: String!) { serviceInstanceRedeploy(environmentId: $environmentId, serviceId: $serviceId) }",
              "variables": {
                "environmentId": "${{ secrets.RAILWAY_ENV_ID }}",
                "serviceId": "${{ secrets.RAILWAY_SERVICE_ID }}"
              }
            }'
